name: Node.js CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install  

      - name: Install k6
        run: |
          curl -s https://packagecloud.io/install/repositories/grafana/stable/script.deb.sh | sudo bash
          sudo apt-get install k6

      - name: Run k6 tests
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: |
          k6 cloud test/ramping_vus_test.js
          k6 cloud test/constant_vus_test.js
          k6 cloud test/constant_arrival_rate_test.js

      - name: Run Node.js tests and collect results
        run: |
          mkdir -p test-results 
          npm test  

      - name: Upload Node.js test results
        uses: actions/upload-artifact@v3  
        with:
          name: test-results  
          path: test-results 

      - name: No build step
        run: echo "No build step necessary for this project"  

      - name: Upload artifact
        uses: actions/upload-artifact@v3  
        with:
          name: project-files
          path: .  

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonarqube-scanner

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ageru666_Lab1-FP \
            -Dsonar.organization=ageru666 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
