name: Node.js CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  

      - name: Start local server
        run: |
          node index.js > server.log 2>&1 &
        env:
          PORT: 8080
          MONGODB_URI: mongodb://localhost:27017/myNewDatabase

      - name: Wait for server to be ready
        run: |
          for i in {1..20}; do
            curl -s http://localhost:8080/external-api/ && break
            echo "Waiting for server..."
            sleep 10
          done

      - name: Show server logs
        run: cat server.log

      - name: Download and install k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.43.1/k6-v0.43.1-linux-amd64.tar.gz -o k6.tar.gz
          tar -xvf k6.tar.gz
          sudo mv k6-v0.43.1-linux-amd64/k6 /usr/local/bin/

      - name: Run k6 constant arrival rate test and save results
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        run: |
          k6 run --out json=constant_arrival_rate_test_result.json test/constant_arrival_rate_test.js

      - name: Run k6 constant VUs test and save results
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        run: |
          k6 run --out json=constant_vus_test_result.json test/constant_vus_test.js

      - name: Run k6 ramping VUs test and save results
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        run: |
          k6 run --out json=ramping_vus_test_result.json test/ramping_vus_test.js

      - name: Upload k6 test results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k6-test-results
          path: |
            constant_arrival_rate_test_result.json
            constant_vus_test_result.json
            ramping_vus_test_result.json
          
      - name: Run Node.js tests and collect results
        run: |
          mkdir -p test-results 
          npm test  

      - name: Upload Node.js test results
        uses: actions/upload-artifact@v3  
        with:
          name: node-test-results  
          path: test-results 

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonarqube-scanner

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ageru666_Lab1-FP \
            -Dsonar.organization=ageru666 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
